name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY_NAME }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_NAME }}/techworkshop:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          registryUrl: ${{ secrets.AZURE_REGISTRY_NAME }}
          registryUsername: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.AZURE_REGISTRY_NAME }}/techworkshop:${{ github.sha }}


      - name: Update Container App environment variables
        run: |
          az containerapp update \
            --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --set-env-vars \
            OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=${{ secrets.OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT }} \
            AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED=${{ secrets.AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED }} \
            FOUNDRY_ENDPOINT=${{ secrets.FOUNDRY_ENDPOINT }} \
            FOUNDRY_API_VERSION=${{ secrets.FOUNDRY_API_VERSION }} \
            gpt_endpoint=${{ secrets.GPT_ENDPOINT }} \
            gpt_deployment=${{ secrets.GPT_DEPLOYMENT }} \
            gpt_api_version=${{ secrets.GPT_API_VERSION }} \
            embedding_endpoint=${{ secrets.EMBEDDING_ENDPOINT }} \
            emdedding_deployment=${{ secrets.EMBEDDING_DEPLOYMENT }} \
            embedding_api_version=${{ secrets.EMBEDDING_API_VERSION }} \
            phi_4_endpoint=${{ secrets.PHI_4_ENDPOINT }} \
            phi_4_deployment=${{ secrets.PHI_4_DEPLOYMENT }} \
            phi_4_api_version=${{ secrets.PHI_4_API_VERSION }} \
            storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }} \
            COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }} \
            DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            CONTAINER_NAME=${{ secrets.CONTAINER_NAME }} \
            APPLICATIONINSIGHTS_CONNECTION_STRING=${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }} \
            customer_loyalty=${{ secrets.CUSTOMER_LOYALTY }} \
            inventory_agent=${{ secrets.INVENTORY_AGENT }} \
            interior_designer=${{ secrets.INTERIOR_DESIGNER }} \
            cora=${{ secrets.CORA }} \
            cart_manager=${{ secrets.CART_MANAGER }} \
            handoff_service=${{ secrets.HANDOFF_SERVICE }} \